# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(388, 410)
        MainWindow.setStyleSheet("backround-color:rgb(255, 170, 0)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_number_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_number_2.setGeometry(QtCore.QRect(110, 220, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cb_number_2.setFont(font)
        self.cb_number_2.setStyleSheet("color:blue;\n"
"backpoundcolor:pink;\n"
"border:2px sold black;\n"
"border-radius:Spx;\n"
"backpound:color rgb(255, 170, 0)")
        self.cb_number_2.setObjectName("cb_number_2")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(100, 70, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color:blue;\n"
"backpoundcolor:pink;\n"
"border:2px sold black;\n"
"border-radius:Spx;\n"
"backpound:color rgb(255, 170, 0)")
        self.title.setObjectName("title")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:blue;\n"
"backpoundcolor:pink;\n"
"border:2px sold black;\n"
"border-radius:Spx;\n"
"backpound:color rgb(255, 170, 0)")
        self.label_2.setObjectName("label_2")
        self.btn_OK = QtWidgets.QPushButton(self.centralwidget)
        self.btn_OK.setGeometry(QtCore.QRect(150, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.btn_OK.setFont(font)
        self.btn_OK.setStyleSheet("color:blue;\n"
"backpoundcolor:pink;\n"
"border:2px sold black;\n"
"border-radius:Spx;\n"
"backpound:color rgb(255, 170, 0)")
        self.btn_OK.setObjectName("btn_OK")
        self.cb_alphabet = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_alphabet.setGeometry(QtCore.QRect(110, 170, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_alphabet.setFont(font)
        self.cb_alphabet.setStyleSheet("color:blue;\n"
"backpoundcolor:pink;\n"
"border:2px sold black;\n"
"border-radius:Spx;\n"
"backpound:color rgb(255, 170, 0)")
        self.cb_alphabet.setObjectName("cb_alphabet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 388, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cb_number_2.setText(_translate("MainWindow", "Використовувати алфавіт"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.label_2.setText(_translate("MainWindow", "Тут буде результат"))
        self.btn_OK.setText(_translate("MainWindow", "Згенерувати"))
        self.cb_alphabet.setText(_translate("MainWindow", "Використовувати числа"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
